#Purpose of this file is store the application URL
#Maintain the application credentials
#Maintain the browser configuration
#Which browser to be used

ReleaseNumber=ABC
Browser=Chrome

Environment = QA

KillExistingBrowsers=True
BrowserClose=True

Incognito=False
Headless=False

ConsolidatedOrIndividualReport=Individual
CaptureScreenshots = True

ScreenResolution=
