#Purpose of this file is store the application URL
#Maintain the application credentials
#Maintain the browser configuration
#Which browser to be used

ReleaseNumber=ABC
Browser=Chrome

URL=https://exa-host-core-exa-dev.apps.ocp-dev.pegadaian.co.id/sign-in
UserName=P89086
Password=Gadai123!@#

KillExistingBrowsers=True
BrowserClose=False

Incognito=False

#Code will be executed in the Background
Headless=False

ConsolidatedOrIndividualReport=Individual

ScreenResolution=

